name: release

on: 
  push:
    tags:
      - "v*.*.*"

env:
  VERSION: "${{github.ref_name}}"

jobs:
  Release-Artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: make release directory
        run: mkdir bin

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build Release Binaries
        run: make build-all

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./bin/*
